config/routes.rb
ProcessMonitor::Application.routes.draw do
  resources :system_processes
  match '/list' => 'system_processes#list', :as => :list
  match '/download/:id' => 'system_processes#download', :as => :download

  mount Resque::Server, at: '/resque'

  root :to => 'system_processes#index'

end

app/models/process_stat.rb
class ProcessStat < ActiveRecord::Base
  attr_accessible :pcpu, :pmem, :system_process_id, :rss, :threads
  belongs_to :system_process
end

app/models/system_process.rb
class SystemProcess < ActiveRecord::Base
  attr_accessible :command, :id, :name, :user
  has_many :process_stats, :dependent => :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/system_processes_controller.rb
class SystemProcessesController < ApplicationController
  def list
    @procs = `ps -ww -e -o pid=,command=`.strip.split("\n").map do |x|
      args = x.split
      {
        pid: args[0].to_i,
        exists: SystemProcess.exists?(args[0].to_i),
        comm: args[1,args.length].join(' ')
      }
    end
  end

  
  def index
    @procs = SystemProcess.all
  end

  def new
    pid = params[:pid]
    comm = params[:comm]
    @proc = SystemProcess.new
    @proc.id = pid
    @proc.command = `ps -ww -p #{pid} -o command=`.strip
  end

  def show
    @proc = SystemProcess.find(params[:id])
    respond_to do |format|
      format.html { @stats = @proc.process_stats.limit(12).reverse_order }
      format.json do |r|
        limit = params[:n]
        if limit
          limit = limit.to_i
        else
          limit = 20
        end
        stats = @proc.process_stats.limit(limit).reverse_order
        render :json => {:data=>stats.as_json}
      end
    end
  end

  def download
    @proc = SystemProcess.find(params[:id])
    stats = @proc.process_stats
    csv_data = "created_at,rss,pmem,pcpu\n"
    stats.each {|s| csv_data << "#{s.created_at},#{s.rss},#{s.pmem},#{s.pcpu}\n" }
    send_data csv_data, :filename => "#{@proc.id}.csv", :type => "text/csv"
  end

  def create
    pid      = params[:system_process][:id].to_i
    tlen     = params[:system_process][:time_length].to_i
    interval = params[:system_process][:interval].to_i
    comm     = params[:system_process][:command]
    @proc = SystemProcess.new
    @proc.id = pid
    @proc.command = comm
    @proc.time_length = tlen
    @proc.interval = interval
    if @proc.save
      Resque.enqueue(MonitorWorker, @proc.id, tlen, interval)
      redirect_to system_process_path pid
    else
      render :new
    end
  end

  def destroy
    @proc = SystemProcess.find(params[:id])
    @proc.destroy
    redirect_to list_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/system_processes_helper.rb
module SystemProcessesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProcessMonitor</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <a href="#" class="brand">Process Monitor</a>
      <ul class="nav">
        <li>
          <%= link_to 'Workers', system_processes_path %>
        </li>
        <li>
          <%= link_to 'Resque', '/resque' %>
        </li>
        <li>
          <%= link_to 'Processes', list_path %>
        </li>
      </ul>
    </div>
  </div>
  <div class='container-fluid'>
    <%= yield %>
  </div>
</body>
</html>

app/views/system_processes/_graph.html.erb
<!-- 
  Make sure to include morris.js and stat_chart.js
-->
<div class="graph-title">
  <h1>
    <% if not params[:label] %>
      RSS
    <% elsif params[:label] == 'rss' %>
      RSS
    <% elsif params[:label] == 'pcpu' %>
      %CPU
    <% elsif params[:label] == 'pmem' %>
      %MEM
    <% end %>
  </h1>
</div>
<%= content_tag :div, "", id: 'process_chart', label: params[:label] || "rss" %>
<%= link_to 'RSS', params.update({label: 'rss'}), class: 'btn graph-switch' %>
<%= link_to '%CPU', params.update({label: 'pcpu'}), class: 'btn graph-switch' %>
<%= link_to '%MEM',params.update({label: 'pmem'}), class: 'btn graph-switch' %>

app/views/system_processes/_stat_table.html.erb
<div class="table-head">
  <h1>System Process <%= @proc.id %></h1>
  <div class='command'>
    <%= @proc.command %>
  </div>
</div>

<div class='reset'>
  <%= link_to 'Reset', @proc, :method=>:delete, :class=>:btn %>
  <%= link_to 'Download', download_path(@proc.id), :class=>:btn %>
</div>

<% if @stats and @stats.length %>
  <table cellspacing="0" id='stat_table' class="table table-striped">
    <thead>
      <th>Time</th>
      <th>RSS</th>
      <th>%Mem</th>
      <th>%CPU</th>
    </thead>
    <tbody>
    </tbody>
  </table>
<% else %>
  <h3> No Stats Available at this time </h3>
<% end %>

app/views/system_processes/create.html.erb
<h1>SystemProcesses#create</h1>
<p>Find me in app/views/system_processes/create.html.erb</p>

app/views/system_processes/index.html.erb
<h1> Monitored Processes </h1>

<table cellspacing="0" class="table table-hover table-striped list-table">
  <thead>
    <th>Process ID</th>
    <th>Command</th>
  </thead>
  <tbody>
    <% @procs.each do |p| %>
      <tr url="<%= url_for system_process_path(p) %>">
        
        <td><%= p.id %></td>
        <td><%= p.command %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/system_processes/list.html.erb
<h1> System Processes </h1>

<table cellspacing="0" class="table table-striped table-hover list-table" id="process-list">
  <thead>
    <th>Process ID</th>
    <th>Monitored</th>
    <th>Command</th>
  </thead>
  <tbody>
    <% @procs.each do |p| %>
      <tr url='<%= url_for new_system_process_path(p)%>'>
        
        <td><%= link_to p[:pid], new_system_process_path(p)%></td>
        <td>
          <% if p[:exists] %>
            <%= link_to 'Monitor', system_process_path(p[:pid])%>
          <% end %>
        </td>
        <td><%= p[:comm] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/system_processes/new.html.erb
<h1><%= @proc.command.split()[0] %></h1>

<h3>Start Process Monitor For <%= @proc.id %></h3>

<div class='command'><%= @proc.command %></div>
<%= form_for @proc do |f| %>
  <%= f.hidden_field :id, value: @proc.id %>
  <%= f.hidden_field :command, value: @proc.command %>

  <%= f.label "Monitor Time (s)" %>
  <%= f.text_field :time_length %>

  <p>

  <%= f.label "Polling interval (s)" %>
  <%= f.text_field :interval %>

  <p>

  <%= f.submit "Launch Monitor"%>
<% end %>

app/views/system_processes/show.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'raphael' %>
  <%= javascript_include_tag 'morris' %>
  <%= javascript_include_tag 'stat_chart' %>
  <%= javascript_include_tag 'stat_table' %>
  <%= javascript_include_tag 'system_processes_show' %>
<% end %>
<div class="row-fluid">
  <div class="span6">
    <%= render 'graph' %>
  </div>
  <div class="span6">
    <div class="spill-cell">
      <%= render 'stat_table' %>
    </div>
  </div>
</div>